#!/usr/bin/env python3
"""
Script que gera arquivos .conf a partir de arquivos JSON.
O nome do arquivo .conf é baseado no campo 'name' do JSON.
"""

import json
import os
import glob
import re
import argparse


def load_triggers_data(triggers_file="triggers_data.json"):
    """Carrega os dados de triggers do arquivo JSON"""
    if os.path.exists(triggers_file):
        with open(triggers_file, 'r', encoding='utf-8') as f:
            return json.load(f)
    return None


def find_triggers_file(map_json_path, triggers_dir="web/triggers"):
    """
    Encontra o arquivo de triggers correspondente ao mapa.
    
    Args:
        map_json_path: Caminho para o arquivo JSON do mapa (ex: web/maps/map.json)
        triggers_dir: Diretório onde procurar os arquivos de triggers (padrão: web/triggers)
    
    Returns:
        Caminho para o arquivo de triggers correspondente ou None se não encontrado
    """
    # Extrai o nome base do arquivo do mapa (sem extensão)
    map_basename = os.path.splitext(os.path.basename(map_json_path))[0]
    
    # Constrói o nome do arquivo de triggers esperado
    triggers_filename = f"{map_basename}_triggers.json"
    triggers_path = os.path.join(triggers_dir, triggers_filename)
    
    if os.path.exists(triggers_path):
        return triggers_path
    
    # Fallback: tenta o arquivo padrão no diretório de triggers
    default_triggers_path = os.path.join(triggers_dir, "triggers_data.json")
    if os.path.exists(default_triggers_path):
        return default_triggers_path
    
    return None


def extract_itemids_from_expression(expression):
    """Extrai itemids de uma expressão de trigger (formato {itemid})"""
    # Procura por padrões como {181566} na expressão
    pattern = r'\{(\d+)\}'
    return re.findall(pattern, expression)


def build_trigger_itemid_map(triggers_data):
    """Constrói um mapeamento triggerid -> lista de itemids"""
    trigger_itemid_map = {}
    if triggers_data and 'triggers' in triggers_data:
        for trigger in triggers_data['triggers']:
            triggerid = trigger.get('triggerid')
            # Usa o array 'functions' que contém os itemids diretamente
            functions = trigger.get('functions', [])
            if triggerid and functions:
                itemids = [func.get('itemid') for func in functions if func.get('itemid')]
                trigger_itemid_map[str(triggerid)] = itemids
    return trigger_itemid_map


def build_trigger_host_map(triggers_data):
    """Constrói um mapeamento triggerid -> host (nome do host)"""
    trigger_host_map = {}
    if triggers_data and 'triggers' in triggers_data:
        for trigger in triggers_data['triggers']:
            triggerid = trigger.get('triggerid')
            hosts = trigger.get('hosts', [])
            if triggerid and hosts:
                # Pega o primeiro host da lista
                host = hosts[0].get('host', '')
                if host:
                    trigger_host_map[str(triggerid)] = host
    return trigger_host_map


def get_bandwidth_from_label(label):
    """
    Determina o valor de BANDWIDTH baseado no label do link.
    
    Args:
        label: Texto do label do link (ex: "1g", "10g", "40g", "100g", "10m", "100m")
    
    Returns:
        String com o valor de BANDWIDTH ou None se não encontrado
    """
    if not label:
        return None
    
    label_lower = label.lower().strip()
    
    bandwidth_map = {
        '1g': '1000M',
        '10g': '10000M',
        '40g': '40000M',
        '100g': '100000M',
        '10m': '10M',
        '100m': '100M'
    }
    
    return bandwidth_map.get(label_lower)


def generate_conf_from_json(json_path, output_dir=".", maps_dir="web/maps"):
    """
    Gera um arquivo .conf a partir de um arquivo JSON.
    
    Args:
        json_path: Caminho para o arquivo JSON
        output_dir: Diretório de saída para o arquivo .conf
        maps_dir: Diretório dos arquivos JSON (usado para encontrar triggers)
    """
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    # Encontra e carrega o arquivo de triggers correspondente
    triggers_file = find_triggers_file(json_path, maps_dir)
    triggers_data = load_triggers_data(triggers_file) if triggers_file else None
    trigger_itemid_map = build_trigger_itemid_map(triggers_data)
    trigger_host_map = build_trigger_host_map(triggers_data)
    
    # Extrai o nome do mapa
    name = data.get('name', 'unknown')
    
    # Gera o conteúdo do arquivo .conf
    conf_content = f"""# Automatically generated by generate_conf.py
# Source: {os.path.basename(json_path)}

FONTDEFINE 100 docs/example/Vera.ttf 8

WIDTH {data.get('width', 1000)}
HEIGHT {data.get('height', 700)}
HTMLSTYLE overlib
KEYFONT 100
TITLE {name}
HTMLOUTPUTFILE {name}.html
IMAGEOUTPUTFILE {name}.png
TIMEPOS 169 26 Created: %b %d %Y %H:%M:%S

KEYPOS DEFAULT 5 5 Traffic Load
KEYTEXTCOLOR 0 0 0
KEYOUTLINECOLOR 0 0 0
KEYBGCOLOR 255 255 255
BGCOLOR 255 255 255
TITLECOLOR 0 0 0
TIMECOLOR 0 0 0
SCALE DEFAULT 0    0    192 192 192  
SCALE DEFAULT 0    1    255 255 255  
SCALE DEFAULT 1    10   140   0 255  
SCALE DEFAULT 10   25    32  32 255  
SCALE DEFAULT 25   40     0 192 255  
SCALE DEFAULT 40   55     0 240   0  
SCALE DEFAULT 55   70   240 240   0  
SCALE DEFAULT 70   85   255 192   0  
SCALE DEFAULT 85  100  255   0   0  

SET nowarn_clipping 1

# End of global section


# TEMPLATE-only NODEs:
NODE DEFAULT
	LABELOFFSET S
	MAXVALUE 100


# TEMPLATE-only LINKs:
LINK DEFAULT
	WIDTH 4
	OVERLIBWIDTH 800
	OVERLIBHEIGHT 300
	ARROWSTYLE compact
	COMMENTSTYLE center
	BWSTYLE angled
	BWFONT 100
	COMMENTFONT 100
	BWOUTLINECOLOR none
	COMMENTFONTCOLOR contrast
	BWLABEL bits
	COMMENTPOS 65 35
	BANDWIDTH 10000M


# regular NODEs:
"""
    
    # Processa os elementos (nós) do mapa
    selements = data.get('selements', [])
    node_names = {}  # Para rastrear nomes únicos
    selementid_to_node = {}  # Mapeamento: selementid -> node_name
    
    for selement in selements:
        label = selement.get('label', '')
        x = selement.get('x', '0')
        y = selement.get('y', '0')
        selementid = selement.get('selementid', '')
        elementtype = selement.get('elementtype', 0)
        selement_label_location = selement.get('label_location', None)
        
        # Ícone padrão
        icon = "images/host.png"
        
        # Determina o label baseado no elementtype
        # elementtype 0 = Host
        if elementtype == '0' and selement.get('elements'):
            elements = selement.get('elements', [])
            if elements and 'hostid' in elements[0]:
                hostid = elements[0]['hostid']
                # Usa o campo 'host' do host como label
                if str(hostid) in trigger_host_map:
                    label = trigger_host_map[str(hostid)]
        
        # Gera nome único para o nó
        node_name = label.replace('{HOST.NAME}', 'host')
        if node_name in node_names:
            # Adiciona sufixo numérico para tornar único
            counter = node_names[node_name] + 1
            node_names[node_name] = counter
            node_name = f"{node_name}_{counter}"
        else:
            node_names[node_name] = 0
        
        # Armazena o mapeamento selementid -> node_name
        if selementid:
            selementid_to_node[str(selementid)] = node_name
        
        # Inclui LABELOFFSET N se o label_location do elemento for 3
        labeloffset_line = ''
        if selement_label_location == '3':
            labeloffset_line = '\tLABELOFFSET N\n'
        
        conf_content += f"""NODE {node_name}
	LABEL {label}
{labeloffset_line}	ICON {icon}
	POSITION {x} {y}
	# selementid: {selementid}

"""
    
    # Processa os links
    links = data.get('links', [])
    if links:
        conf_content += "# regular LINKs:\n"
        # Dicionário para garantir nomes únicos de links
        link_name_counts = {}
        for i, link in enumerate(links):
            selementid1 = link.get('selementid1', '')
            selementid2 = link.get('selementid2', '')
            
            # Tenta obter nodes da lista 'nodes' (formato antigo)
            nodes = link.get('nodes', [])
            if len(nodes) >= 2:
                node1 = nodes[0].split(':')[0] if ':' in nodes[0] else nodes[0]
                node2 = nodes[1].split(':')[0] if ':' in nodes[1] else nodes[1]
            elif selementid1 and selementid2:
                # Usa o mapeamento selementid -> node_name
                node1 = selementid_to_node.get(str(selementid1), f'node_{selementid1}')
                node2 = selementid_to_node.get(str(selementid2), f'node_{selementid2}')
            else:
                continue
            
            # Busca itemids e hosts dos linktriggers
            linktriggers = link.get('linktriggers', [])
            itemids = []
            trigger_hosts = []
            for linktrigger in linktriggers:
                triggerid = linktrigger.get('triggerid')
                if triggerid and str(triggerid) in trigger_itemid_map:
                    itemids.extend(trigger_itemid_map[str(triggerid)])
                    # Busca o host associado a este trigger
                    if str(triggerid) in trigger_host_map:
                        trigger_hosts.append(trigger_host_map[str(triggerid)])
            
            # Remove duplicatas mantendo a ordem
            seen = set()
            unique_itemids = []
            for itemid in itemids:
                if itemid not in seen:
                    seen.add(itemid)
                    unique_itemids.append(itemid)
            
            # Remove duplicatas de hosts mantendo a ordem
            seen_hosts = set()
            unique_hosts = []
            for host in trigger_hosts:
                if host not in seen_hosts:
                    seen_hosts.add(host)
                    unique_hosts.append(host)
            
            # Constrói a URL do gráfico com os itemids encontrados
            if unique_itemids:
                itemids_params = '&'.join([f'itemids[{i}]={itemid}' for i, itemid in enumerate(unique_itemids)])
                graph_url = f"http://zabbix.iper.net.br:8070/zabbix/chart.php?from=now-24h&to=now&{itemids_params}&type=0&profileIdx=web.item.graph.filter&profileIdx2=0&batch=1&width=800&height=200"
            else:
                graph_url = "http://zabbix.iper.net.br:8070/zabbix/chart.php?from=now-24h&to=now&itemids[0]=0&itemids[1]=0&type=0&profileIdx=web.item.graph.filter&profileIdx2=0&batch=1&width=800&height=200"
            
            # Constrói a linha TARGET com host e itemids
            if unique_hosts and unique_itemids:
                # Usa o primeiro host e os itemids
                host_for_target = unique_hosts[0]
                itemids_for_target = ':'.join(unique_itemids)
                target_line = f"TARGET zabbix:itemid:{host_for_target}:{itemids_for_target}"
            elif unique_itemids:
                itemids_for_target = ':'.join(unique_itemids)
                target_line = f"TARGET zabbix:itemid:{node1}:{itemids_for_target}"
            else:
                target_line = f"TARGET zabbix:itemid:{node1}:0:0"
            
            # Extrai o primeiro nome do TARGET (o host)
            # Formato: zabbix:itemid:HOST:ITEMID1:ITEMID2
            target_parts = target_line.split(':')
            first_target_name = target_parts[2] if len(target_parts) > 2 else node1
            
            # Reordena node1 e node2 para que o primeiro seja o mesmo do TARGET
            # Se o host do TARGET não está em node1, troca as posições
            if first_target_name != node1:
                node1, node2 = node2, node1
            
            # Gera nome do link baseado nos IDs (agora com node1 sendo o host do TARGET)
            base_link_name = f"{node1}-{node2}"
            # Garante unicidade adicionando sufixo numérico se necessário
            count = link_name_counts.get(base_link_name, 0)
            if count == 0:
                link_name = base_link_name
            else:
                link_name = f"{base_link_name}_{count}"
            # Atualiza contador para o próximo link com o mesmo nome base
            link_name_counts[base_link_name] = count + 1
            
            # Obtém o label do link para determinar o BANDWIDTH
            link_label = link.get('label', '')
            bandwidth_value = get_bandwidth_from_label(link_label)
            
            # Constrói a seção do LINK
            link_section = f"""LINK {link_name}
	OVERLIBGRAPH {graph_url}
	{target_line}
	NODES {node1} {node2}
"""
            
            # Adiciona BANDWIDTH se encontrado
            if bandwidth_value:
                link_section += f"\tBANDWIDTH {bandwidth_value}\n"
            
            link_section += "\n"
            conf_content += link_section
    
    conf_content += "# That's All Folks!\n"
    
    # Escreve o arquivo .conf
    conf_filename = f"{name}.conf"
    conf_path = os.path.join(output_dir, conf_filename)
    
    with open(conf_path, 'w', encoding='utf-8') as f:
        f.write(conf_content)
    
    print(f"Gerado: {conf_path}")
    return conf_path


def main():
    """Processa arquivos JSON na pasta web/maps/"""
    # Configura argumentos de linha de comando
    parser = argparse.ArgumentParser(
        description="Gera arquivos .conf a partir de arquivos JSON do Zabbix",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Exemplos de uso:
  python generate_conf.py                              # Processa todos os arquivos em web/maps/
  python generate_conf.py -f web/maps/atm.json         # Processa apenas um arquivo específico
  python generate_conf.py -m web/maps/ -o configs/     # Especifica diretórios de entrada e saída
        """
    )
    parser.add_argument(
        '-f', '--file',
        type=str,
        help='Caminho para um arquivo JSON específico a ser processado (opcional)'
    )
    parser.add_argument(
        '-m', '--maps-dir',
        type=str,
        default='web/maps',
        help='Diretório contendo os arquivos JSON dos mapas (padrão: web/maps)'
    )
    parser.add_argument(
        '-o', '--output',
        type=str,
        default='configs',
        help='Diretório de saída para os arquivos .conf (padrão: configs)'
    )
    
    args = parser.parse_args()
    
    # Cria a pasta de saída se não existir
    output_dir = args.output
    os.makedirs(output_dir, exist_ok=True)
    
    # Determina quais arquivos processar
    if args.file:
        # Processa apenas o arquivo especificado
        json_files = [args.file]
        if not os.path.exists(args.file):
            print(f"Erro: Arquivo não encontrado: {args.file}")
            return
    else:
        # Processa todos os arquivos JSON na pasta web/maps/
        json_files = glob.glob(os.path.join(args.maps_dir, "*.json"))
    
    if not json_files:
        print("Nenhum arquivo JSON encontrado")
        return
    
    print(f"Encontrados {len(json_files)} arquivo(s) JSON para processar")
    
    for json_file in json_files:
        try:
            generate_conf_from_json(json_file, output_dir=output_dir, maps_dir=args.maps_dir)
        except Exception as e:
            print(f"Erro ao processar {json_file}: {e}")


if __name__ == "__main__":
    main()